---
env_vars:
  WANDB_API_KEY: ""
  R2_ACCOUNT_ID: ""
  R2_GRADIENTS_ACCOUNT_ID: ""
  R2_GRADIENTS_BUCKET_NAME: ""
  R2_READ_ACCESS_KEY_ID: ""
  R2_READ_SECRET_ACCESS_KEY: ""
  R2_GRADIENTS_READ_ACCESS_KEY_ID: ""
  R2_GRADIENTS_READ_SECRET_ACCESS_KEY: ""
  R2_WRITE_ACCESS_KEY_ID: ""
  R2_WRITE_SECRET_ACCESS_KEY: ""
  R2_GRADIENTS_WRITE_ACCESS_KEY_ID: ""
  R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY: ""
  R2_DATASET_WRITE_ACCESS_KEY_ID: ""
  R2_DATASET_WRITE_SECRET_ACCESS_KEY: ""
  R2_DATASET_ACCOUNT_ID: "80f15715bb0b882c9e967c13e677ed7d"
  R2_DATASET_BUCKET_NAME: "80f15715bb0b882c9e967c13e677ed7d"
  R2_DATASET_READ_ACCESS_KEY_ID: "88548d962edc9a1f4416cbb3453d914a"
  R2_DATASET_READ_SECRET_ACCESS_KEY: "4934ae848465113a75babf7d0a88efd9112aa49296c900744268e91f1d31998f"
  WALLET_NAME: ""
  NETWORK: "finney"
  NETUID: "3"
  DEBUG: "false"
  GITHUB_USER: ""
  # CUDA_DEVICE: ""
  # WALLET_HOTKEY: ""

# Whether to use Systemd or not
use_systemd: false

# Miner cli parameters
actual_batch_size: 5
netuid: "3"
subtensor_network: "finney"
wallet_name: ""

# device: "cuda"
# wallet_hotkey: ""
cuda_devices: ["cuda:0"]
wallet_hotkeys: ["miner_0"]

apt_packages:
  - less
  - vim
  - nvtop
  - htop
  - rsync
  - git
  - python3-pip
  - python3-venv
  - zsh

additional_apt_packages: []

# Global pip packages to install (via pip3)
essential_pip_packages:
  - uv

additional_pip_packages: []

# Pip packages to install in .venv with `uv pip`.
additional_uv_pip_packages: []
